use std::{
    sync::{
        atomic::{self, AtomicBool, AtomicUsize, Ordering},
        mpsc::{sync_channel, SyncSender},
        Arc,
    },
    thread,
    time::Duration,
};

use basedrop::{Collector, Handle, Owned};
use crossbeam_queue::ArrayQueue;
use dashmap::DashMap;

use crate::{
    effect::Effect,
    error::Error,
    output::OutputDevice,
    source::{
        amplified::AmplifiedSource,
        converted::ConvertedSource,
        file::FileSource,
        mixed::{MixedSource, MixerMessage},
        panned::PannedSource,
        playback::PlaybackMessageQueue,
        resampled::ResamplingQuality,
        status::{PlaybackStatusContext, PlaybackStatusEvent},
        synth::SynthSource,
    },
    Generator, Source,
};

// -------------------------------------------------------------------------------------------------

mod handles;

// -------------------------------------------------------------------------------------------------

/// Unique ID for played back file, synth or generator sources.
pub type PlaybackId = usize;

/// Unique ID for newly added mixers.
pub type MixerId = usize;

/// Unique ID for newly added effects.
pub type EffectId = usize;

// Playback handles for sources.
pub use handles::{
    EffectHandle, FilePlaybackHandle, GeneratorPlaybackHandle, SourcePlaybackHandle,
    SynthPlaybackHandle,
};

// -------------------------------------------------------------------------------------------------

/// How to move an effect within a mixer.
pub enum EffectMovement {
    /// Negative value shift the effect towards the start, positive ones towards the end.
    Direction(i32),
    /// Move effect to the start of the effect chain.
    Start,
    /// Move effect to the end of the effect chain.
    End,
}

// -------------------------------------------------------------------------------------------------

/// Player internal info about a currently playing source.
struct PlayingSource {
    is_playing: Arc<AtomicBool>,
    playback_message_queue: PlaybackMessageQueue,
}

impl Drop for PlayingSource {
    fn drop(&mut self) {
        // NB: this only works when Self is not clone or copy, so we can ensure that an object
        // isn't created temporarily and then dropped again!!
        self.is_playing.store(false, Ordering::Relaxed);
    }
}

// -------------------------------------------------------------------------------------------------

/// Playback controller, which continuously fills an [`OutputDevice`]s stream with audio data
/// generated by one or more [`Source`](crate::Source)s.
///
/// It can play an unlimited number of [`FileSource`] or [`SynthSource`] sources and allows
/// monitoring playback position via an optional [`PlaybackStatusEvent`] [`sync_channel`].
///
/// When starting to play a source a [`FilePlaybackHandle`] or [`SynthPlaybackHandle`] is returned
/// which allows checking if the source is still playing, or to stop it, or to change playback runtime
/// properties such as volume/pan and pitch.
///
/// The player also supports creating complex DSP graphs by adding sub-mixers and [`Effect`]s.
/// Initially, a `Player` contains a single main mixer only. You can add effects to this mixer
/// using [`add_effect`](Self::add_effect). Audio sources played without specifying a target mixer
/// will be routed through the main mixer and its effects.
///
/// To create more advanced routing, you can add new mixers as sub-mixers to existing ones
/// using [`add_mixer`](Self::add_mixer). Each mixer can have its own chain of effects. When
/// playing a source, you can specify a `target_mixer` in the playback options to direct its output
/// to a specific sub-mixer. This allows for parallel processing paths, such as applying different
/// effects to different groups of sounds.
pub struct Player {
    output_device: Box<dyn OutputDevice>,
    playing_sources: Arc<DashMap<PlaybackId, PlayingSource>>,
    playback_status_sender: SyncSender<PlaybackStatusEvent>,
    collector_handle: Handle,
    collector_running: Arc<AtomicBool>,
    mixer_event_queues: Arc<DashMap<MixerId, Arc<ArrayQueue<MixerMessage>>>>,
    mixer_effects: Arc<DashMap<EffectId, (MixerId, Option<&'static str>)>>,
}

impl Player {
    /// The ID of the main mixer, which is always present.
    const MAIN_MIXER_ID: MixerId = 0;

    /// Create a new player for the given [`OutputDevice`]. Param `playback_status_sender` is an optional
    /// channel which can be used to receive playback status events for the currently playing sources.
    pub fn new<S: Into<Option<SyncSender<PlaybackStatusEvent>>>>(
        output_device: impl OutputDevice + 'static,
        playback_status_sender: S,
    ) -> Self {
        // Memorize the sink
        let mut output_device = Box::new(output_device);

        // Create a proxy for the playback status channel, so we can trap stop messages
        let playing_sources = Arc::new(DashMap::with_capacity(1024));
        let playback_status_sender =
            Self::handle_playback_events(playback_status_sender.into(), playing_sources.clone());

        // Create audio garbage collector and thread
        let collector = Collector::new();
        let collector_handle = collector.handle();
        let collector_running = Arc::new(AtomicBool::new(true));
        Self::handle_drop_collects(collector, collector_running.clone());

        // Create a mixer source and add it to the audio sink
        let main_mixer =
            MixedSource::new(output_device.channel_count(), output_device.sample_rate());
        let mixer_event_queue = main_mixer.message_queue();
        let mixer_event_queues = Arc::new(DashMap::new());
        mixer_event_queues.insert(Self::MAIN_MIXER_ID, mixer_event_queue);

        let mixer_effects = Arc::new(DashMap::new());

        // assign our main mixer as sink source
        output_device.play(Box::new(main_mixer));

        Self {
            output_device,
            playing_sources,
            playback_status_sender,
            collector_handle,
            collector_running,
            mixer_event_queues,
            mixer_effects,
        }
    }

    /// Our audio device's suspended state.
    pub fn output_suspended(&self) -> bool {
        self.output_device.is_suspended()
    }

    /// Our audio device's actual sample rate.
    pub fn output_sample_rate(&self) -> u32 {
        self.output_device.sample_rate()
    }
    /// Our audio device's actual sample channel count.
    pub fn output_channel_count(&self) -> usize {
        self.output_device.channel_count()
    }
    /// Our actual playhead pos in samples (NOT sample frames)
    pub fn output_sample_position(&self) -> u64 {
        self.output_device.sample_position()
    }
    /// Our actual playhead pos in sample frames
    pub fn output_sample_frame_position(&self) -> u64 {
        self.output_sample_position() / self.output_channel_count() as u64
    }

    /// Our output's global volume factor
    pub fn output_volume(&self) -> f32 {
        self.output_device.volume()
    }
    /// Set a new global volume factor
    pub fn set_output_volume(&mut self, volume: f32) {
        assert!(volume >= 0.0);
        self.output_device.set_volume(volume);
    }

    /// Get a copy of our playback status sender channel.
    /// Should be used by custom audio sources only.
    pub fn playback_status_sender(&self) -> SyncSender<PlaybackStatusEvent> {
        self.playback_status_sender.clone()
    }

    /// Start audio playback.
    pub fn is_running(&self) -> bool {
        self.output_device.is_running()
    }

    /// Start audio playback.
    pub fn start(&mut self) {
        self.output_device.resume();
    }

    /// Stop audio playback. This will only pause and thus not drop any playing sources. Use the
    /// `start` function to start it again. Use function `stop_all_sources` to drop all sources.
    pub fn stop(&mut self) {
        self.output_device.pause();
    }

    /// Play a newly created or cloned file source.
    pub fn play_file_source<F: FileSource, T: Into<Option<u64>>>(
        &mut self,
        file_source: F,
        start_time: T,
    ) -> Result<FilePlaybackHandle, Error> {
        self.play_file_source_with_context(file_source, start_time, None)
    }
    /// Play a newly created or cloned file source with the given playback status context.
    pub fn play_file_source_with_context<F: FileSource, T: Into<Option<u64>>>(
        &mut self,
        file_source: F,
        start_time: T,
        context: Option<PlaybackStatusContext>,
    ) -> Result<FilePlaybackHandle, Error> {
        let mixer_id = file_source
            .playback_options()
            .target_mixer
            .unwrap_or(Self::MAIN_MIXER_ID);
        let mixer_event_queue = self.mixer_event_queue(mixer_id)?;
        // make sure the source has a valid playback status channel
        let mut file_source = file_source;
        if file_source.playback_status_sender().is_none() {
            file_source.set_playback_status_sender(Some(self.playback_status_sender.clone()));
        }
        // set playback context
        file_source.set_playback_status_context(context);
        // memorize source in playing sources map
        let playback_id = file_source.playback_id();
        let playback_volume = file_source.playback_options().volume;
        let playback_panning = file_source.playback_options().panning;
        let playback_message_queue = file_source.playback_message_queue();
        // convert file to mixer's rate and channel layout
        let converted_source = ConvertedSource::new(
            file_source,
            self.output_device.channel_count(),
            self.output_device.sample_rate(),
            ResamplingQuality::Default,
        );
        // apply volume options
        let amplified_source = AmplifiedSource::new(converted_source, playback_volume);
        let volume_message_queue = amplified_source.message_queue();
        // apply panning options
        let panned_source = PannedSource::new(amplified_source, playback_panning);
        let panning_message_queue = panned_source.message_queue();
        // add to playing sources
        let is_playing = Arc::new(AtomicBool::new(true));
        let playback_message_queue = PlaybackMessageQueue::File {
            playback: playback_message_queue,
            volume: volume_message_queue,
            panning: panning_message_queue,
        };
        self.playing_sources.insert(
            playback_id,
            PlayingSource {
                is_playing: Arc::clone(&is_playing),
                playback_message_queue: playback_message_queue.clone(),
            },
        );
        // send the source to the mixer
        let source = Owned::new(
            &self.collector_handle,
            Box::new(panned_source) as Box<dyn Source>,
        );
        let sample_time = start_time.into().unwrap_or(0);
        if mixer_event_queue
            .push(MixerMessage::AddSource {
                playback_id,
                playback_message_queue: playback_message_queue.clone(),
                source,
                sample_time,
            })
            .is_err()
        {
            self.playing_sources.remove(&playback_id);
            Err(Self::mixer_event_queue_error("play_file"))
        } else {
            // Create and return handle
            let mixer_event_queues = Arc::clone(&self.mixer_event_queues);
            Ok(FilePlaybackHandle::new(
                is_playing,
                playback_id,
                mixer_id,
                playback_message_queue,
                mixer_event_queues,
            ))
        }
    }

    /// Play a newly created or cloned synth source with the given playback options.
    pub fn play_synth_source<S: SynthSource, T: Into<Option<u64>>>(
        &mut self,
        synth_source: S,
        start_time: T,
    ) -> Result<SynthPlaybackHandle, Error> {
        self.play_synth_source_with_context(synth_source, start_time, None)
    }
    /// Play a newly created or cloned synth source with the given playback options and
    /// playback status context.
    pub fn play_synth_source_with_context<S: SynthSource, T: Into<Option<u64>>>(
        &mut self,
        synth_source: S,
        start_time: T,
        context: Option<PlaybackStatusContext>,
    ) -> Result<SynthPlaybackHandle, Error> {
        let mixer_id = synth_source
            .playback_options()
            .target_mixer
            .unwrap_or(Self::MAIN_MIXER_ID);
        let mixer_event_queue = self.mixer_event_queue(mixer_id)?;
        // make sure the source has a valid playback status channel
        let mut synth_source = synth_source;
        if synth_source.playback_status_sender().is_none() {
            synth_source.set_playback_status_sender(Some(self.playback_status_sender.clone()));
        }
        synth_source.set_playback_status_context(context);
        // memorize source in playing sources map
        let playback_id = synth_source.playback_id();
        let playback_volume = synth_source.playback_options().volume;
        let playback_panning = synth_source.playback_options().panning;
        let playback_message_queue = synth_source.playback_message_queue();
        // convert file to mixer's rate and channel layout
        let converted_source = ConvertedSource::new(
            synth_source,
            self.output_device.channel_count(),
            self.output_device.sample_rate(),
            ResamplingQuality::Default, // usually unused
        );
        // apply volume options
        let amplified_source = AmplifiedSource::new(converted_source, playback_volume);
        let volume_message_queue = amplified_source.message_queue();
        // apply panning options
        let panned_source = PannedSource::new(amplified_source, playback_panning);
        let panning_message_queue = panned_source.message_queue();
        // add to playing sources
        let is_playing = Arc::new(AtomicBool::new(true));
        let playback_message_queue = PlaybackMessageQueue::Synth {
            playback: playback_message_queue,
            volume: volume_message_queue,
            panning: panning_message_queue,
        };
        self.playing_sources.insert(
            playback_id,
            PlayingSource {
                is_playing: Arc::clone(&is_playing),
                playback_message_queue: playback_message_queue.clone(),
            },
        );
        // send the source to the mixer
        let source = Owned::new(
            &self.collector_handle,
            Box::new(panned_source) as Box<dyn Source>,
        );
        let sample_time = start_time.into().unwrap_or(0);
        if mixer_event_queue
            .push(MixerMessage::AddSource {
                playback_id,
                playback_message_queue: playback_message_queue.clone(),
                source,
                sample_time,
            })
            .is_err()
        {
            self.playing_sources.remove(&playback_id);
            Err(Self::mixer_event_queue_error("play_synth"))
        } else {
            // Create and return handle
            let mixer_event_queues = Arc::clone(&self.mixer_event_queues);
            Ok(SynthPlaybackHandle::new(
                is_playing,
                playback_id,
                mixer_id,
                playback_message_queue,
                mixer_event_queues,
            ))
        }
    }

    /// Play a generator source.
    ///
    /// Returns a handle that can be used to control the generator, e.g. to stop it or to send
    /// events to trigger or stop individual notes.
    ///
    /// Use `mixer_id` to specify which mixer to add the generator to. If None, adds to the main mixer.
    pub fn play_generator_source<
        G: Generator + 'static,
        M: Into<Option<MixerId>>,
        T: Into<Option<u64>>,
    >(
        &mut self,
        generator: G,
        mixer_id: M,
        start_time: T,
    ) -> Result<GeneratorPlaybackHandle, Error> {
        let mixer_id = mixer_id.into().unwrap_or(Self::MAIN_MIXER_ID);
        let mixer_event_queue = self.mixer_event_queue(mixer_id)?;
        // make sure the source has a valid playback status channel
        let mut generator = generator;
        if generator.playback_status_sender().is_none() {
            generator.set_playback_status_sender(Some(self.playback_status_sender.clone()));
        }
        // get source in playback id and message channel
        let playback_id = generator.playback_id();
        let playback_message_queue = generator.playback_message_queue();
        // convert generator to mixer's rate and channel layout
        let converted_source = ConvertedSource::new(
            generator,
            self.output_device.channel_count(),
            self.output_device.sample_rate(),
            ResamplingQuality::Default,
        );
        // apply initial volume
        let initial_volume = 1.0;
        let amplified_source = AmplifiedSource::new(converted_source, initial_volume);
        let volume_message_queue = amplified_source.message_queue();
        // apply initial panning
        let panning = 0.0;
        let panned_source = PannedSource::new(amplified_source, panning);
        let panning_message_queue = panned_source.message_queue();
        // add to playing sources
        let is_playing = Arc::new(AtomicBool::new(true));
        let playback_message_queue = PlaybackMessageQueue::Generator {
            playback: playback_message_queue,
            volume: volume_message_queue,
            panning: panning_message_queue,
        };
        self.playing_sources.insert(
            playback_id,
            PlayingSource {
                playback_message_queue: playback_message_queue.clone(),
                is_playing: Arc::clone(&is_playing),
            },
        );
        // send the source to the mixer
        let source = Owned::new(
            &self.collector_handle,
            Box::new(panned_source) as Box<dyn Source>,
        );
        let sample_time = start_time.into().unwrap_or(0);
        if mixer_event_queue
            .push(MixerMessage::AddSource {
                playback_id,
                playback_message_queue: playback_message_queue.clone(),
                source,
                sample_time,
            })
            .is_err()
        {
            self.playing_sources.remove(&playback_id);
            Err(Self::mixer_event_queue_error("play_generator"))
        } else {
            // Create and return handle
            let mixer_event_queues = Arc::clone(&self.mixer_event_queues);
            Ok(GeneratorPlaybackHandle::new(
                is_playing,
                playback_id,
                mixer_id,
                playback_message_queue,
                mixer_event_queues,
                self.collector_handle.clone(),
            ))
        }
    }

    /// Add a new mixer to an existing mixer.
    /// Use `None` as mixer id to add it to the main mixer.
    pub fn add_mixer<M: Into<Option<MixerId>>>(
        &mut self,
        parent_mixer_id: M,
    ) -> Result<MixerId, Error> {
        let parent_mixer_id = parent_mixer_id.into().unwrap_or(Self::MAIN_MIXER_ID);
        let parent_mixer_event_queue = self.mixer_event_queue(parent_mixer_id)?;

        let mixer = Box::new(MixedSource::new(
            self.output_channel_count(),
            self.output_sample_rate(),
        ));
        let mixer_queue = mixer.message_queue();
        let mixer_id = Self::unique_mixer_id();

        // Send message to parent mixer
        if parent_mixer_event_queue
            .push(MixerMessage::AddMixer { mixer_id, mixer })
            .is_err()
        {
            Err(Self::mixer_event_queue_error("add_mixer"))
        } else {
            self.mixer_event_queues.insert(mixer_id, mixer_queue);
            self.mixer_effects.insert(mixer_id, (parent_mixer_id, None));

            Ok(mixer_id)
        }
    }

    /// Remove a mixer and all its effects from its parent mixer.
    pub fn remove_mixer(&mut self, mixer_id: MixerId) -> Result<(), Error> {
        // Can't remove the main mixer
        if mixer_id == Self::MAIN_MIXER_ID {
            return Err(Error::ParameterError(
                "Cannot remove the main mixer".to_string(),
            ));
        }

        // Find the parent mixer
        let parent_mixer_id = self
            .mixer_effects
            .get(&mixer_id)
            .map(|entry| entry.value().0)
            .ok_or(Error::MixerNotFoundError(mixer_id))?;

        let parent_mixer_event_queue = self.mixer_event_queue(parent_mixer_id)?;

        // Send the remove message to parent
        if parent_mixer_event_queue
            .push(MixerMessage::RemoveMixer { mixer_id })
            .is_err()
        {
            Err(Self::mixer_event_queue_error("remove_mixer"))
        } else {
            // Remove all effects that belong to this mixer
            let effects_to_remove: Vec<EffectId> = self
                .mixer_effects
                .iter()
                .filter_map(|entry| {
                    let (effect_id, (owner_mixer_id, _)) = (entry.key(), entry.value());
                    if *owner_mixer_id == mixer_id {
                        Some(*effect_id)
                    } else {
                        None
                    }
                })
                .collect();

            for effect_id in effects_to_remove {
                self.mixer_effects.remove(&effect_id);
            }

            // Remove the mixer from tracking maps
            self.mixer_event_queues.remove(&mixer_id);
            self.mixer_effects.remove(&mixer_id);

            Ok(())
        }
    }

    /// Remove all sub-mixers from the given mixer.
    /// Use `None` as mixer_id to remove all sub-mixers from the main mixer.
    pub fn remove_all_mixers<M: Into<Option<MixerId>>>(
        &mut self,
        mixer_id: M,
    ) -> Result<(), Error> {
        let mixer_id = mixer_id.into().unwrap_or(Self::MAIN_MIXER_ID);

        // Find all sub-mixers that have this mixer as their parent
        let sub_mixers_to_remove: Vec<MixerId> = self
            .mixer_effects
            .iter()
            .filter_map(|entry| {
                let (sub_mixer_id, (parent_mixer_id, effect_name)) = (entry.key(), entry.value());
                // A mixer entry has None as effect_name
                if *parent_mixer_id == mixer_id && effect_name.is_none() {
                    Some(*sub_mixer_id)
                } else {
                    None
                }
            })
            .collect();

        // Remove each sub-mixer
        for sub_mixer_id in sub_mixers_to_remove {
            self.remove_mixer(sub_mixer_id)?;
        }

        Ok(())
    }

    /// Add an effect to the given mixer's output.
    /// Use `None` as mixer_id to add the effect to the main mixer.
    pub fn add_effect<E: Effect, M: Into<Option<MixerId>>>(
        &mut self,
        effect: E,
        mixer_id: M,
    ) -> Result<EffectHandle, Error> {
        let mixer_id = mixer_id.into().unwrap_or(Self::MAIN_MIXER_ID);
        let mixer_event_queue = self.mixer_event_queue(mixer_id)?;

        let channel_count = self.output_channel_count();
        // The effect's parent mixer uses a temp buffer of size:
        let max_frames = MixedSource::MAX_MIX_BUFFER_SAMPLES / channel_count;

        let effect_name = effect.name();
        let mut effect = Owned::new(&self.collector_handle, Box::new(effect) as Box<dyn Effect>);
        effect.initialize(self.output_sample_rate(), channel_count, max_frames)?;

        let effect_id = Self::unique_effect_id();
        if mixer_event_queue
            .push(MixerMessage::AddEffect { effect_id, effect })
            .is_err()
        {
            Err(Self::mixer_event_queue_error("add_effect"))
        } else {
            self.mixer_effects
                .insert(effect_id, (mixer_id, Some(effect_name)));

            // Create and return handle
            Ok(EffectHandle::new(
                effect_id,
                mixer_id,
                effect_name,
                Arc::clone(&self.mixer_event_queues),
                self.collector_handle.clone(),
            ))
        }
    }

    /// Move an effect within the given mixer's effect list to reorder the processing chain.
    pub fn move_effect<M: Into<Option<MixerId>>>(
        &mut self,
        movement: EffectMovement,
        effect_id: EffectId,
        mixer_id: M,
    ) -> Result<(), Error> {
        let mixer_id = mixer_id.into().unwrap_or(Self::MAIN_MIXER_ID);

        // Verify the effect exists and belongs to the specified mixer
        let (effect_mixer_id, _) = *self
            .mixer_effects
            .get(&effect_id)
            .ok_or(Error::EffectNotFoundError(effect_id))?
            .value();

        if effect_mixer_id != mixer_id {
            return Err(Error::ParameterError(format!(
                "Effect {} does not belong to mixer {}",
                effect_id, mixer_id
            )));
        }

        let mixer_event_queue = self.mixer_event_queue(mixer_id)?;

        // Send the move message to the mixer
        if mixer_event_queue
            .push(MixerMessage::MoveEffect {
                effect_id,
                movement,
            })
            .is_err()
        {
            Err(Self::mixer_event_queue_error("move_effect"))
        } else {
            Ok(())
        }
    }

    /// Remove an effect from the given mixer.
    pub fn remove_effect(&mut self, effect_id: EffectId) -> Result<(), Error> {
        // Send the remove message
        if self
            .effect_mixer_event_queue(effect_id)?
            .push(MixerMessage::RemoveEffect { effect_id })
            .is_err()
        {
            Err(Self::mixer_event_queue_error("remove_effect"))
        } else {
            // Remove from tracking map
            self.mixer_effects.remove(&effect_id);
            Ok(())
        }
    }

    /// Remove all effects from the given mixer.
    /// Use `None` as mixer_id to remove all effects from the main mixer.
    pub fn remove_all_effects<M: Into<Option<MixerId>>>(
        &mut self,
        mixer_id: M,
    ) -> Result<(), Error> {
        let mixer_id = mixer_id.into().unwrap_or(Self::MAIN_MIXER_ID);

        // Find all effects belonging to this mixer
        let effects_to_remove = self
            .mixer_effects
            .iter()
            .filter_map(|entry| {
                let (effect_id, (owner_mixer_id, _)) = (entry.key(), entry.value());
                if *owner_mixer_id == mixer_id {
                    Some(*effect_id)
                } else {
                    None
                }
            })
            .collect::<Vec<_>>();

        // Remove each effect
        for effect_id in effects_to_remove {
            self.remove_effect(effect_id)?;
        }

        Ok(())
    }

    /// Immediately stop all playing and possibly scheduled sources.
    pub fn stop_all_sources(&mut self) -> Result<(), Error> {
        // stop everything that is playing now
        for playing_source in self.playing_sources.iter() {
            let _ = playing_source.playback_message_queue.send_stop();
        }
        self.playing_sources.clear();
        // remove all upcoming, scheduled sources in all mixers too (force push stop events!)
        for queue in self.mixer_event_queues.iter() {
            if queue
                .value()
                .force_push(MixerMessage::RemoveAllPendingSources)
                .is_some()
            {
                log::warn!("Mixer's event queue is full.");
                log::warn!("Increase the mixer event queue to prevent this from happening...");
            }
        }
        Ok(())
    }

    fn handle_playback_events(
        playback_sender: Option<SyncSender<PlaybackStatusEvent>>,
        playing_sources: Arc<DashMap<PlaybackId, PlayingSource>>,
    ) -> SyncSender<PlaybackStatusEvent> {
        // use a relatively big bounded channel for playback status tracking
        const DEFAULT_PLAYBACK_EVENTS_CAPACITY: usize = 1024;
        let (playback_sender_proxy, playback_receiver_proxy) =
            sync_channel(DEFAULT_PLAYBACK_EVENTS_CAPACITY);

        std::thread::Builder::new()
            .name("audio_player_messages".to_string())
            .spawn(move || loop {
                if let Ok(event) = playback_receiver_proxy.recv() {
                    if let PlaybackStatusEvent::Stopped { id, .. } = event {
                        playing_sources.remove(&id);
                    }
                    if let Some(sender) = &playback_sender {
                        // NB: send and not try_send: block until sender queue is free
                        if let Err(err) = sender.send(event) {
                            log::warn!("Failed to send file status message: {err}");
                        }
                    }
                } else {
                    log::info!("Playback event loop stopped");
                    break;
                }
            })
            .expect("Failed to spawn audio message thread");

        playback_sender_proxy
    }

    fn handle_drop_collects(mut collector: Collector, running: Arc<AtomicBool>) {
        std::thread::Builder::new()
            .name("audio_player_drops".to_string())
            .spawn(move || {
                while running.load(atomic::Ordering::Relaxed) {
                    collector.collect();
                    thread::sleep(Duration::from_millis(100));
                }
                log::info!("Audio collector loop stopped");
                collector.collect();
                if collector.try_cleanup().is_err() {
                    log::warn!("Failed to cleanup collector");
                }
            })
            .expect("Failed to spawn audio message thread");
    }

    /// Get a clone of the mixer event queue for the given mixer ID.
    fn mixer_event_queue(&self, mixer_id: MixerId) -> Result<Arc<ArrayQueue<MixerMessage>>, Error> {
        Ok(Arc::clone(
            self.mixer_event_queues
                .get(&mixer_id)
                .ok_or(Error::MixerNotFoundError(mixer_id))?
                .value(),
        ))
    }

    fn effect_mixer_event_queue(
        &self,
        effect_id: EffectId,
    ) -> Result<Arc<ArrayQueue<MixerMessage>>, Error> {
        let (mixer_id, _) = *self
            .mixer_effects
            .get(&effect_id)
            .ok_or(Error::EffectNotFoundError(effect_id))?
            .value();
        self.mixer_event_queue(mixer_id)
    }

    fn mixer_event_queue_error(event_name: &str) -> Error {
        log::warn!("Mixer's event queue is full. Failed to send a {event_name} event.");
        log::warn!("Increase the mixer event queue to prevent this from happening...");

        Error::SendError("Mixer queue is full".to_string())
    }

    fn unique_mixer_id() -> MixerId {
        static ID_COUNTER: AtomicUsize = AtomicUsize::new(1);
        ID_COUNTER.fetch_add(1, atomic::Ordering::Relaxed)
    }

    fn unique_effect_id() -> EffectId {
        static ID_COUNTER: AtomicUsize = AtomicUsize::new(1);
        ID_COUNTER.fetch_add(1, atomic::Ordering::Relaxed)
    }
}

impl Drop for Player {
    fn drop(&mut self) {
        // stop collector thread
        self.collector_running
            .store(false, atomic::Ordering::Relaxed);
        // stop playback thread and release mixer source
        self.output_device.close();
    }
}
